DEBUG: true
DB:
  WRITE: "root:default_password@(mysqlserver:3306)/si_test?charset=utf8&parseTime=True&loc=Local"
  READ: "root:default_password@(mysqlserver:3306)/si_test?charset=utf8&parseTime=True&loc=Local"
BASE_URL: "http://localhost:8000"
